[context.production]
command = "npx prisma generate && npx prisma db seed && npm run build"

[context.deploy-preview]
command = "npx prisma generate && npm run build"

[build]
   publish = ".next"
   ignore = "/bin/false"


[[plugins]]
  package = "@netlify/plugin-nextjs"