import ServerComponentExample from "@/components/ServerComponentExample";
import "./globals.css";
import AuthProvider from "@/components/AuthProviders";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  
  console.log("Session: ",session)

  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <ServerComponentExample session={session}/>
          {children}
          </body>
      </AuthProvider>
    </html>
  );
}
